# Generated by Django 2.1.3 on 2019-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('prepaid_shows_amount', models.IntegerField()),
                ('categories', models.TextField()),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
