# Generated by Django 2.1.3 on 2019-02-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
